# For configuration options and examples please see:
# https://github.com/benphelps/homepage/wiki/Services

- Proxmox:
    - PVE 'essentials-node':
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Smart-Home and cloud services
    - PVE 'main-node':
        icon: proxmox.png
        href: https://192.168.2.191:8006
        description: Smart-Home and cloud services
    - PVE 'network-node':
        icon: proxmox.png
        href: https://192.168.2.202:8006
        description: Networking services
    - PVE 'storage-node'':
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Storage and testing services
    - Proxmox 'Backup Server':
        icon: proxmox.png
        href: https://192.168.2.199:8007
        description: Backup server for PVE nodes

- AI:
    - Insanely Fast Whisper:
        icon: /icons/insanely-fast-whisper.png
        href: http://192.168.2.110:7860
        description: Fast speech-to-text transcription
    - Parakeet ROCm:
        icon: /icons/parakeet-nemo-icon.png
        href: http://192.168.2.110:7861
        description: Fast speech-to-text transcription
    - Open WebUI:
        icon: /icons/open-webui.png
        href: http://192.168.2.110:3000
        description: Offline, feature-rich, extensible WebUI

- Smart Home:
    - Home Assistant 'Prod':
        icon: home-assistant.png
        href: https://ha.beecave.nl
        description: The main Home Assistant server
    - Home Assistant 'Test':
        icon: home-assistant.png
        href: http://192.168.2.20:8123
        description: Home Assistant test server
    - Zigbee2mqtt:
        icon: zigbee2mqtt.png
        href: http://192.168.2.152:9442
        description: Zigbee network controller
    - Scrypted:
        icon: scrypted.png
        href: https://192.168.2.169:10443
        description: Use IP cameras in HomeKit
    - ESPHome:
        icon: esphome.png
        href: http://192.168.2.171:6052
        description: ESPHome webui

- Network:
    - pi-hole:
        icon: pi-hole.png
        href: http://192.168.2.200/admin
        description: Recursive DNS with unbound and adblocking.
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://192.168.2.184:3001
        description: Check if hosts are up
    - Omada:
        icon: omada.png
        href: https://192.168.2.10:8043
        description: Omada software controller
    - Crowdsec:
        icon: crowdsec.png
        href: https://192.168.2.175
        description: Crowsec Security Client
    - Speed Test:
        icon: openspeedtest.png
        href: http://192.168.2.186:5216
        description: Self hosted speedtest service
    - Netboot:
        icon: netboot.png
        href: http://192.168.2.185:3000
        description: Netboot webui

- Download and Convert:
    - Qbittorrent-nox:
        icon: qbittorrent.png
        href: http://192.168.2.192:8090
        description: Torrent server
    - Qbittorrent-nox (ao):
        icon: qbittorrent.png
        href: http://192.168.2.223:8090
        description: Torrent server that is always on
    - Handbrake:
        icon: handbrake.png
        href: http://192.168.2.130:5800
        description: Convert mediafiles to different formats

- Arrs:
    - Bazarr:
        icon: bazarr.png
        href: http://192.168.2.41:6767
        description: Automatic subtitle downloader for Sonarr and Radarr
    - Lidarr:
        icon: lidarr.png
        href: http://192.168.2.42:8686
        description: Automatic music downloader for usenet and torrents
    - Prowlarr:
        icon: prowlarr.png
        href: http://192.168.2.43:9696
        description: Automatic indexing of usenet and torrent trackers
    - Radarr:
        icon: radarr.png
        href: http://192.168.2.44:7878
        description: Automatic movie downloader for usenet and torrents
    - Readarr:
        icon: readarr.png
        href: http://192.168.2.45:8787
        description: Automatic e-book downloader for usenet and torrents
    - Sonarr:
        icon: sonarr.png
        href: http://192.168.2.46:8989
        description: Automatic series downloader for usenet and torrents
    - Tdarr:
        icon: tdarr.png
        href: http://192.168.2.47:8265
        description: Automatic transcoder for Radarr and Sonarr
    - Whisparr:
        icon: whisparr.png
        href: http://192.168.2.48:6969
        description: Automatic xxx downloader for usenet and torrents

- Storage:
    - Truenas:
        icon: truenas.png
        href: https://192.168.2.195
        description: Storage server
    - Nextcloud:
        icon: nextcloud.png
        href: https://192.168.2.175
    - Pingvin:
        icon: pingvin.png
        href: https://transfer.beecave.nl
        description: Transfer, share and request files safely.

- Mediaplayer and photo's:
    - Plex:
        icon: plex.png
        href: http://192.168.2.194:32400/web
        description: Plex Media Server
    - Jellyfin:
        icon: jellyfin.png
        href: http://192.168.2.22:8096
        description: Jellyfin Media Server for the family
    - Jellyfin-PM:
        icon: jellyfin.png
        href: http://192.168.2.24:8096
        description: Jellyfin Media Server for PM
    - Photoprism:
        icon: photoprism.png
        href: http://192.168.2.135:2342
        description: Photo collection with person recognition.

- Other:
    - Planka:
        icon: planka.png
        href: http://192.168.2.56:3000
        description: Kaban project board
    - Excalidraw:
        icon: excalidraw.png
        href: http://192.168.2.51:3000
        description: Virtual collaborative whiteboard and diagrams tool.
    - Whoogle:
        icon: whooglesearch.png
        href: http://192.168.2.197:5000
        description: Private search engine
    - Olivetin:
        icon: olivetin.png
        href: http://192.168.2.179:1337
        description: Command and control dashboard
    - Slimme Lezer:
        icon: https://www.zuidwijk.com/wp-content/uploads/2020/12/cropped-Logo-MZuidwijk.com_-1-1.png
        href: http://192.168.0.2/home.html
        description: Electricity and gas consumption meter

- Games:
    - EmulatorJS:
        icon: emulatorjs.png
        href: http://192.168.2.183
        description: Retroarch emulator running in a Javascript webapp
    - Turnkey-Gameserver:
        icon: turnkey-gameserver.png
        href: ""
        description: Turnkey gameserver for MineOS

- Proxmox guests:
    - 101 local-ai (qemu):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox QEMU guest 101 on pve-storage
    - 102 netboot-xyz (qemu):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox QEMU guest 102 on pve-storage
    - 103 hermes-agent (qemu):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox QEMU guest 103 on pve-storage
    - 104 truenas-core (qemu):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox QEMU guest 104 on pve-storage
    - 250 homeassistant (qemu):
        icon: proxmox.png
        href: https://192.168.2.191:8006
        description: Running Proxmox QEMU guest 250 on pve-main
    - 500 sanitize-text (qemu):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox QEMU guest 500 on pve-essentials
    - 120 photoprism (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 120 on pve-storage
    - 121 esphome (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 121 on pve-storage
    - 123 myspeed (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 123 on pve-storage
    - 129 metube (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 129 on pve-storage
    - 130 searxng (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 130 on pve-storage
    - 131 handbrake (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 131 on pve-storage
    - 133 plex (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 133 on pve-storage
    - 135 qbittorrent (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 135 on pve-storage
    - 137 bazarr (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 137 on pve-storage
    - 138 lidarr (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 138 on pve-storage
    - 139 prowlarr (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 139 on pve-storage
    - 140 radarr (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 140 on pve-storage
    - 141 readarr (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 141 on pve-storage
    - 142 sonarr (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 142 on pve-storage
    - 144 whisparr (lxc):
        icon: proxmox.png
        href: https://192.168.2.190:8006
        description: Running Proxmox LXC guest 144 on pve-storage
    - 201 olivetin (lxc):
        icon: proxmox.png
        href: https://192.168.2.191:8006
        description: Running Proxmox LXC guest 201 on pve-main
    - 202 scrypted (lxc):
        icon: proxmox.png
        href: https://192.168.2.191:8006
        description: Running Proxmox LXC guest 202 on pve-main
    - 204 zigbee2mqtt (lxc):
        icon: proxmox.png
        href: https://192.168.2.191:8006
        description: Running Proxmox LXC guest 204 on pve-main
    - 205 planka (lxc):
        icon: proxmox.png
        href: https://192.168.2.191:8006
        description: Running Proxmox LXC guest 205 on pve-main
    - 206 piper-tts (lxc):
        icon: proxmox.png
        href: https://192.168.2.191:8006
        description: Running Proxmox LXC guest 206 on pve-main
    - 207 airconnect (lxc):
        icon: proxmox.png
        href: https://192.168.2.191:8006
        description: Running Proxmox LXC guest 207 on pve-main
    - 300 pi-hole (lxc):
        icon: proxmox.png
        href: https://192.168.2.202:8006
        description: Running Proxmox LXC guest 300 on pve-network
    - 301 cloudflared (lxc):
        icon: proxmox.png
        href: https://192.168.2.202:8006
        description: Running Proxmox LXC guest 301 on pve-network
    - 302 homepage-local (lxc):
        icon: proxmox.png
        href: https://192.168.2.202:8006
        description: Running Proxmox LXC guest 302 on pve-network
    - 303 uptimekuma (lxc):
        icon: proxmox.png
        href: https://192.168.2.202:8006
        description: Running Proxmox LXC guest 303 on pve-network
    - 304 nginx-proxy-manager (lxc):
        icon: proxmox.png
        href: https://192.168.2.202:8006
        description: Running Proxmox LXC guest 304 on pve-network
    - 309 whoogle (lxc):
        icon: proxmox.png
        href: https://192.168.2.202:8006
        description: Running Proxmox LXC guest 309 on pve-network
    - 310 mqtt (lxc):
        icon: proxmox.png
        href: https://192.168.2.202:8006
        description: Running Proxmox LXC guest 310 on pve-network
    - 311 nextcloudpi (lxc):
        icon: proxmox.png
        href: https://192.168.2.202:8006
        description: Running Proxmox LXC guest 311 on pve-network
    - 312 pingvin-ao (lxc):
        icon: proxmox.png
        href: https://192.168.2.202:8006
        description: Running Proxmox LXC guest 312 on pve-network
    - 405 excalidraw (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 405 on pve-essentials
    - 407 jellyfin-pm (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 407 on pve-essentials
    - 409 nedap-docs-proxy (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 409 on pve-essentials
    - 411 SMB-fileserver (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 411 on pve-essentials
    - 414 linkwarden (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 414 on pve-essentials
    - 416 wish-this (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 416 on pve-essentials
    - 417 gogs (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 417 on pve-essentials
    - 418 qbittorrent-ao (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 418 on pve-essentials
    - 420 rallly (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 420 on pve-essentials
    - 421 alpine-vaultwarden (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 421 on pve-essentials
    - 424 namer (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 424 on pve-essentials
    - 428 blog (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 428 on pve-essentials
    - 429 qdrant (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 429 on pve-essentials
    - 430 vid2gif (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 430 on pve-essentials
    - 431 vid2audio (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 431 on pve-essentials
    - 433 srt-pipeline (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 433 on pve-essentials
    - 434 git-gains (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 434 on pve-essentials
    - 435 proxmox-pwa (lxc):
        icon: proxmox.png
        href: https://192.168.2.203:8006
        description: Running Proxmox LXC guest 435 on pve-essentials
